### ISSUE TITLE
tohoku-221104 do not exist anymore

### ISSUE THREAD

**Issue by francois-baptiste** [glassonion1/osrm-server-demo#1]
Thanks for sharing this great project!
An error though, `tohoku-221104` can't be downloaded anymore, I had to use `tohoku-latest`.

**Comment by glassonion1** [comment]
Thanks for your comment. The readme was wrong, so I fixed it.

**Comment by francois-baptiste** [comment]
Great! I think you will also also need to fix the reference to `tohoku-221104` in `compose.yaml`

**Comment by glassonion1** [comment]
Oh sure. I've fixed compose.yaml as well.
